//
//          Copyright Seth Hendrick 2018.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)
//

using System;
using System.Reflection;
using Mono.Options;

namespace Filesing.Cli
{
    class Program
    {
        static int Main( string[] args )
        {
            try
            {
                bool showHelp = false;
                bool showVersion = false;
                bool showLicense = false;

                OptionSet options = new OptionSet
                {
                    { "h|help", "Shows this message and exits.", h => showHelp = ( h != null ) },
                    { "version", "Shows the version and exits.", v => showVersion = ( v != null ) },
                    { "license", "Shows the license information and exits.", l => showLicense = ( l != null ) }
                };

                options.Parse( args );

                // Help will take precedence, followed by version, then
                // license.
                if( showHelp )
                {
                    options.WriteOptionDescriptions( Console.Out );
                }
                else if( showVersion )
                {
                    ShowVersion();
                }
                else if( showLicense )
                {
                    ShowLicense();
                }
                else
                {

                }
            }
            catch( OptionException e )
            {
                Console.WriteLine( e.Message );
                return -1;
            }
            catch( Exception e )
            {
                Console.WriteLine( "FATAL ERROR: " + e.Message );
                return -2;
            }

            return 0;
        }

        private static void ShowLicense()
        {
            const string license = 
@"Filesing - Copyright Seth Hendrick 2018.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the ""Software"") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED ""AS IS"", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
";
            Console.WriteLine(license);
        }

        private static void ShowVersion()
        {
            Console.WriteLine(
                Assembly.GetExecutingAssembly().GetName().Version
            );
        }
    }
}
